export const REQUEST_INDEX = 'REQUEST_POST_INDEX';
export const RESPONSE_INDEX = 'RESPONSE_POST_INDEX';
export const REQUEST_SHOW = 'REQUEST_POST_SHOW';
export const RESPONSE_SHOW = 'RESPONSE_POST_SHOW';